// Artworks data - auto-generated by Python script
// DO NOT EDIT MANUALLY - this file is overwritten by clean_artworks.py

const ARTWORKS_DATA = [
    { filename: "sample_art_1.jpg", artist: "Dream Fan Artist", description: "Happy Birthday Dream! Amazing speedrun celebration art", link: "https://twitter.com/elevenisrising", path: "assets/artworks/sample_art_1.jpg" },
    { filename: "sample_art_2.jpg", artist: "MinecraftMaster", description: "Epic manhunt chase scene with Dream\'s signature moves", link: "https://twitter.com/elevenisrising", path: "assets/artworks/sample_art_2.jpg" },
    { filename: "sample_art_3.jpg", artist: "PixelCreator", description: "Beautiful portrait of Dream with his iconic smile", link: "https://twitter.com/elevenisrising", path: "assets/artworks/sample_art_3.jpg" },
    { filename: "sample_art_4.jpg", artist: "ArtisticDreamer", description: "Dream SMP birthday party with all the characters", link: "https://twitter.com/elevenisrising", path: "assets/artworks/sample_art_4.jpg" },
    { filename: "HokusNotTaken.png", artist: "HokusNotTaken", description: "For this piece I wanted to play around with colors, making the backround and the character very distinct from each other. Since the backround is green, I chose to make Dream and the balloons the opposite color - red :]", link: "https://x.com/HokusNotTaken?t=CzgVwnsgLr_5nL704LEuXw&s=09", path: "assets/artworks/HokusNotTaken.png" },
    { filename: "YNKATcj.png", artist: "YNKATcj", description: "Amazing artwork by YNKATcj", link: "https://x.com/lynkatcj?s=21&t=UfjJ-MyQwaNifZRW5rvs3w", path: "assets/artworks/YNKATcj.png" }
];

// Export for use in main script
window.ARTWORKS_DATA = ARTWORKS_DATA;
